# docker-compose.yml
version: '3'
services:
  rabbit:
    image: rabbitmq:3
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - rabbit
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password