# docker-compose.yml
version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=crowd
      - RABBITMQ_DEFAULT_PASS=crowd123
    ports:
      - 5672:5672
      - 15672:15672
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - rabbit
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password